apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
  labels:
    app: ci-cd-app
spec:
  type: LoadBalancer
  selector:
    app: ci-cd-app
  ports:
    - protocol: TCP
      port: 80         # Exposes port 80 externally
      targetPort: 5000 # Maps to the container's port 5000
